POST http://localhost:4001/products 
content-type: application/json

{
  "name": "Uva verde",
  "price": 10.90
}

###
GET http://localhost:4001/products

###
GET http://localhost:4001/products/c3029ecf-943e-4aff-8571-9623a3c88c98

###
PUT http://localhost:4001/products/c3029ecf-943e-4aff-8571-9623a3c88c98
content-type: application/json

{
  "name": "Uva verde amarela",
  "price": 78.30
}

###

DELETE http://localhost:4001/products/100ec002-0f82-488c-b7ba-33340e996563
